### ISSUE TITLE
I want to ask how to solve this error pop-up

### ISSUE THREAD

**Issue by Savingoften** [articulateinstruments/AAA-DeepLabCut-Resources#1]
I want to ask how to solve this error pop-up
<img width="1280" alt="微信图片_20221219202828" src="https://user-images.githubusercontent.com/92630184/208426276-d9f212d4-e2ba-4780-9e49-dda7d1e56fee.png">

**Comment by aawrench** [comment]
It is possible that this error occured in version 220_04_01 because of an unsafe divide in drawing the glossometer display. We have fixed this unsafe divide in version 220_04_02 which can be downloaded from the website.
